### ISSUE TITLE
Support for ALBERT

### ISSUE THREAD

**Issue by shiju80** [kamalkraj/BERT-NER-TF#2]
Hi Kamal,
Is it possible to load Albert Tf1.0 model found here - https://github.com/google-research/google-research/tree/master/albert
for NER training.

**Comment by kamalkraj** [comment]
Hi @shiju80,
I just finished converting Albert model to TF 2.0 and tested with TF hub weights.
Both produce identical results. 
Will release all the task training, including  NER. with TF 2.0 soon.

**Comment by shiju80** [comment]
Thanks @kamalkraj , looking forward to trying it out.

**Comment by kamalkraj** [comment]
@shiju80 ALBERT is not suitable for NER task.  All the models they released are uncased
https://github.com/kamalkraj/ALBERT-TF2.0

**Comment by shiju80** [comment]
oh ok Thanks @kamalkraj
