### ISSUE TITLE
Tensorflow serving Request

### ISSUE THREAD

**Issue by niranjan8129** [kamalkraj/BERT-NER-TF#5]
Hi Kamal, I  very much like your work and model and making as public. 
Just have a request 

1) Could you please **add tenser flow serving** on this model for deployment ?
2) I ran against google colab and got error b2low 
**RuntimeError: Error copying tensor to device: /job:localhost/replica:0/task:0/device:GPU:0. /job:localhost/replica:0/task:0/device:GPU:0 unknown device.**

Did I do any mistake for colab setting or need to change the **run_ner.py** file?

Regards,
Niranjan

**Comment by kamalkraj** [comment]
@niranjan8129 
2 error is due to cuda and tf version incompatibility

**Comment by niranjan8129** [comment]
Thank you a lot !!!
