### ISSUE TITLE
Opinionated HTTP server 

### ISSUE THREAD

**Issue by donutloop** [kamalkraj/BERT-NER-TF#6]
In my point of view! This package shouldn't contain an HTTP API because you are using a very opinionated framework to expose your model via an API. Let the users decide what they want to use as an HTTP Framework.  

This HTTP API isn't configurable for example Ner("out_base") parameter, exposed route, "CORS", HTTP port, response payload, and request object can be changed without package changes. 

For example, I don't want to use Flask as Framework and to install any dependencies regardings Flask so, please modify the python requirements and get rid of this api.py.

**Comment by kamalkraj** [comment]
Thanks. I just want to show how to deploy the model as REST API.
